-- IPL Data Analysis Project
-- Dataset: IPL Matches and Deliveries (2008-2022)
-- Total Matches: 1095 | Total Deliveries: 260920

-- Q1: Matches played per season
SELECT SEASON, COUNT(ID) AS total_matches 
FROM MATCHES GROUP BY SEASON ORDER BY SEASON;

-- Q2: Team with most wins
SELECT WINNER, COUNT(WINNER) AS total_wins 
FROM MATCHES GROUP BY WINNER 
ORDER BY COUNT(WINNER) DESC LIMIT 1;

-- Q3: City with most matches hosted
SELECT CITY, COUNT(CITY) AS total_matches 
FROM MATCHES GROUP BY CITY 
ORDER BY COUNT(CITY) DESC LIMIT 1;

-- Q4: Player with most Player of the Match awards
SELECT PLAYER_OF_MATCH, COUNT(PLAYER_OF_MATCH) AS total_awards 
FROM MATCHES GROUP BY PLAYER_OF_MATCH 
ORDER BY COUNT(PLAYER_OF_MATCH) DESC LIMIT 1;

-- Q5: Wins by runs vs wickets per team
SELECT WINNER, RESULT, COUNT(*) AS total_wins
FROM MATCHES GROUP BY WINNER, RESULT ORDER BY WINNER;

-- Q6: Venue with most matches
SELECT VENUE, COUNT(VENUE) AS total_matches 
FROM MATCHES GROUP BY VENUE 
ORDER BY COUNT(VENUE) DESC LIMIT 1;

-- Q7: Top 10 batsmen by total runs
SELECT BATTER, SUM(BATSMAN_RUNS) AS total_runs 
FROM DELIVERIES GROUP BY BATTER 
ORDER BY SUM(BATSMAN_RUNS) DESC LIMIT 10;

-- Q8: Top 10 bowlers by total wickets
SELECT BOWLER, SUM(IS_WICKET) AS total_wickets 
FROM DELIVERIES GROUP BY BOWLER 
ORDER BY SUM(IS_WICKET) DESC LIMIT 10;

-- Q9: Team with most total runs scored
SELECT BATTING_TEAM, SUM(TOTAL_RUNS) AS total_runs 
FROM DELIVERIES GROUP BY BATTING_TEAM 
ORDER BY SUM(TOTAL_RUNS) DESC LIMIT 1;

-- Q10: Average runs per match per season
SELECT M.SEASON, ROUND(AVG(d.MATCH_RUNS), 2) AS avg_runs_per_match
FROM MATCHES M
JOIN (
    SELECT MATCH_ID, SUM(TOTAL_RUNS) AS MATCH_RUNS
    FROM DELIVERIES GROUP BY MATCH_ID
) D ON M.ID = D.MATCH_ID
GROUP BY M.SEASON
ORDER BY M.SEASON;